### ISSUE TITLE
Make locale comparison case-insensitive

### ISSUE THREAD

**Issue by rbaprado** [mashpie/i18n-node#128]
Hello,

I had a pretty hard time figuring out that the function guessLanguage is case sensitive (debugging node is definitely not funny), I would suggest to change that...

Regards,
Renato

**Comment by MickMonaghan** [comment]
Hi @monkpow, 
Doesn't the `preserveLegacyCase` change you submitted only apply to language codes passed via a query parameter? The issue still exists when parsing the `Accept-Language` header - right?

@mashpie - great module, super useful.
As per [BCP47](https://tools.ietf.org/html/bcp47#section-2.1.1), all language tags should be treated case insensitively. Can we have this issue labeled a bug instead of feature request?

**Comment by monkpow** [comment]
Yes, the patch I presented only addressed query param.    I can't speak to if an issue still exists when parsing the ```Accept-Language``` header.
