### ISSUE TITLE
Need more granular defaults

### ISSUE THREAD

**Issue by colynb** [mashpie/i18n-node#137]
I was expecting the "defaultLocale" setting to allow me to set a locale to fallback to if a requested key was not available in the chosen language. For example, say I have set up two locales: en-us and de-ch. If I have a key in the en file 

```
{
  ...
   "greeting" : "Hello!"
  ...
}
```

But do not have the same key in the de file, and my selected locale is de-ch, I want the a request for ```__('greeting')``` to default to the english one. This doesn't appear to be a feature in your module, yet this is a common practice.

**Comment by AoDev** [comment]
Hi, I have encountered another somehow bad consequence of this behaviour.

If  the option `updateFiles` is active, then every time that someone visits with a different language setting, the app will generate a new locale file for that language. Then, since no translation is provided, the whole interface displays the keys instead of meaningful texts. I think that anyone would expect to see the default language strings when this happens.

**Comment by mashpie** [comment]
updateFiles should be used in dev only

--
mobil beantwortet

**Comment by mashpie** [comment]
please consider fallbacks: https://github.com/mashpie/i18n-node/blob/master/test/i18n.fallbacks.js

**Comment by nobso** [comment]
> Hi, I have encountered another somehow bad consequence of this behaviour.
> 
> If the option `updateFiles` is active, then every time that someone visits with a different language setting, the app will generate a new locale file for that language. Then, since no translation is provided, the whole interface displays the keys instead of meaningful texts. I think that anyone would expect to see the default language strings when this happens.

Hi @AoDev , How did you resolve your requirement? The 'fallbacks' option is for the locale and not for the strings, right?
