### ISSUE TITLE
How can I override the locale using the query string?

### ISSUE THREAD

**Issue by rbaprado** [mashpie/i18n-node#185]
Hello,

I am looking into ways of providing alternate language url in my sitemap.xml to please googlebot. I supposed 18n provides an easy way to do it but I could not figure it out from the documentation...

**Comment by mashpie** [comment]
there is an undocumented feature in i18n api. Take a look at https://github.com/mashpie/i18n-node/blob/master/i18n.js#L324

You should be able to switch locales by appending `?locale=en` to any url. That feature is not yet covered by tests and might get some improvements in future, like configuring the parameter name etc.

Another option is to implement your own middleware and switch with `i18n.setLocale()`

**Comment by rbaprado** [comment]
Thanks Marcus. I will look inro it.

2015-11-27 6:38 GMT-02:00 Marcus Spiegel <notifications@github.com>:

**Comment by robertwbradford** [comment]
I'm using `lang` as the query string parameter name so I have the following:
```
app.use(function(req, res, next) {
  req.setLocale(req.query.lang);
  // Make the current locale available in the response object locals.
  res.locals.locale = req.getLocale();
  next();
})
```

**Comment by mashpie** [comment]
officially supported by now, see https://github.com/mashpie/i18n-node#list-of-all-configuration-options and https://github.com/mashpie/i18n-node/blob/master/test/i18n.configureQueryParameter.js

**Comment by markschmid** [comment]
Using this feature too. If the query parameter is set, the locale is overridden, but a call to `getLocale()` is not reflecting the override, it's showing the locale according to what `init()` thinks that the locale should be.
E.g. when I use `?lang=de`, the page is displayed in German, but `getLocale()` is returning "en", since that's what is set as `accept-language` of the browser.

How do I determine the locale that's really used for displaying the page?

**Comment by mashpie** [comment]
it will probably be one of:

```js
i18n.getLocale(req);
i18n.getLocale(res);
i18n.getLocale(res.locals);
```

or accordingly

```js
req.getLocale();
res.getLocale();
res.locals.getLocale();
```

which object is bound totally depends on your setup

**Comment by markschmid** [comment]
Thanks!
