### ISSUE TITLE
Zero Plural "0 thing"

### ISSUE THREAD

**Issue by fridays** [mashpie/i18n-node#190]
```javascript
console.log(__n('%d thing', '%d things', 1)); // 1 thing
console.log(__n('%d thing', '%d things', 2)); // 2 things
console.log(__n('%d thing', '%d things', 0)); // 0 thing
```
I was expecting ```0 things```.

Am I doing something wrong?

**Comment by kulakowka** [comment]
:+1: 
It would be great if it will be possible to specify translation to zero.

```
"%s replies": {
		"zero": "no replies",
		"one": "%s reply",
		"other": "%s replies"
	},
```

**Comment by pyhedgehog** [comment]
It would be even greater to support more translations for different rules. #178

**Comment by mashpie** [comment]
"zero" will be part of "other" soon, probably like so:

```json
"%s replies": {
    "zero": "no replies",
    "one": "%s reply",
    "other": "%s replies"
}

"%s replies": {
    "one": "%s reply",
    "other": "{0} no replies|%s replies"
}
```

**Comment by mashpie** [comment]
..had to edit my last comment `[0]` instead of `{0}` for now...your PR is master. 

So i18n now officially follows https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localization_and_Plurals => __Plural rule No1__ as default. Before your patch it followed _Plural rule No2_ To get a fallback for our french friends I 1st added support for ranges, so our famous cat would give:

`// de.json`
```json
{
    "%s cat": {
        "one": "%s Katze",
        "other": "%s Katzen"
    },
}
```
```js
__d('%s cat', 0) // --> 0 Katzen
__d('%s cat', 1) // --> 1 Katze
__d('%s cat', 5) // --> 5 Katzen
```

for french as example those should get changed into

`// fr.json`
```json
{
    "%s cat": {
        "one": "%s chat",
        "other": "[0] %s chat|%s chats"
    },
}
```

or even shorter

`// fr.json`
```json
{
    "%s cat": "[0,1] %s chat|%s chats"
}
```
```js
__d('%s cat', 0) // --> 0 chat
__d('%s cat', 1) // --> 1 chat
__d('%s cat', 5) // --> 5 chats
```

another use in german could also be:

`// de.json`
```json
{
    "%s cat": {
        "one": "%s Katze",
        "other": "[0] keine Katze|%s Katzen"
    },
}
```
```js
__d('%s cat', 0) // --> keine Katze
__d('%s cat', 1) // --> 1 Katze
__d('%s cat', 5) // --> 5 Katzen
```

I'd be so happy, if you find time to also review https://github.com/mashpie/i18n-node#ranged-interval-support.

And for real plural rules I will give a try to https://www.npmjs.com/package/make-plural for integration.
