### ISSUE TITLE
Local json file overwritten from time to time

### ISSUE THREAD

**Issue by mitomm** [mashpie/i18n-node#266]
I'm not sure when it happens, but my local json (en.json / de.json) get overwritten from time to time, such that the JSON values are the same as the keys.

Any ideas on where this is coming from or how i can avoid it? Because it is super annoying to get my work overwritten randomly. 

Although the following is a fork of this repo, maybe it helps to resolve the issue (since it seems related):

https://github.com/jeresig/i18n-node-2/issues/39

Thanks for any help.

**Comment by mashpie** [comment]
see https://github.com/mashpie/i18n-node#i18nconfigure esp. 

```
    // whether to write new locale information to disk - defaults to true
    updateFiles: false,
```

keeps i18n from touching your files completely. Root cause could be any error in you scripts and/or json files. Please ensure that you json files are valid to strict json specs, like using `"` and not `'`, don't have trailing commas or comments.

One possible scenario might be: A wrong typed json file get's read by i18n. An empty locale object get's initiated due to json-parsing-errors and as soon any `i18n.__()` get invoked i18n writes back a new json file but with freshly initiated object containing keys only.

The config setting will safe you from destroying your data. But i18n might not work until you fix the root cause of that error.

**Comment by mitomm** [comment]
Thanks for the quick reply.

Didn't know about "updateFiles: false".

Setting it to false should then resolve my issue.

**Comment by vmjames** [comment]
I also had this problem but in fact it was due to my json file having a comma missing! When I set "updateFiles: false" all of my translations where undefined.. :(

**Comment by ReFruity** [comment]
Should be `updateFiles: false` by default
