### ISSUE TITLE
Multi instance of i18n

### ISSUE THREAD

**Issue by rimiti** [mashpie/i18n-node#324]
When the module is used in a project and the project has a module which use i18n module too, there are automatically some conflicts because the `require` function return Singleton....

It could be fun to add a function to create multiple instances of the module like this fork.
https://www.npmjs.com/package/i18n-factory 

Why do not integrate this feature in the official package?

Regards,

**Comment by ieugen** [comment]
We have a project where translations are split into multiple files because each set is updated differently - some texts need manual/human validations and some we can deploy as soon as they are translated.

We need a way have multiple instances of i18n.

**Comment by ieugen** [comment]
I found this issue that offers an alternative: - merge the json files as part of a build process .
However, I find this practice sub-optimal for my case since when I have to update the translations I have a build step instead of a simple copy step. 

I also have to duplicate / maintain this step inside the repo and maybe as a prodcution binary. 
There are solutions to this but why do that when a simple copy would work ok - if i18n has support for returning `new` objects instead of the singleton - which should be easy to do IMO.

**Comment by mashpie** [comment]
now... feature is released as of 0.12.0 with some extra sugar (shortcut to i18n.configure on creation):

```js
const { I18n } = require("i18n");

const i18n = new I18n({
    locales:['en', 'de'],
    directory: __dirname + '/locales'
});
```

see https://github.com/mashpie/i18n-node/tree/master#as-instance for details

**Comment by rimiti** [comment]
Great! 
Thank you @mashpie

**Comment by TheInvoker** [comment]
Is there a typescript example, it is not working for me in typescript. Says I18n is not available as an export from the class.

**Comment by mashpie** [comment]
@TheInvoker - unfortunately no. you may see https://github.com/mashpie/i18n-node/issues/444 for details. I do want to provide proper definitions, but right now there are only 3rd party ones which get outdated with each new release...
