### ISSUE TITLE
the "debug" dependency is specified as "*"

### ISSUE THREAD

**Issue by liuzhen2008** [mashpie/i18n-node#381]
Thanks to the recent updates in debug, it introduces syntax not compatible with v4.x.x node runtime.

Please do not use version * as dependency or move it to devDependency.

I think right now all the v4.x.x node running anything that uses your package directly or indirectly as dependency is now breaking.. 😢😢😢

Thanks

**Comment by clagosarias** [comment]
Having exactly the same issue.
Last working version of debug dependency (for my project) was 3.1.0.

Can't deploy to prod now... 😢  waiting for a response or will try to fork it.

**Comment by somprabhsharma** [comment]
Facing same issue. Unable to deploy to prod because of this. Please fix this @mashpie

**Comment by somprabhsharma** [comment]
@mashpie Submitted PR for this - https://github.com/mashpie/i18n-node/pull/382

**Comment by mashpie** [comment]
**Workaround:**

installing the older version of debug as direct dependency to your project prevents i18n fetching newest debug version as dep:

`npm i debug@3.2.5 -S`

nodejs v4 is end-of-life since april, see https://github.com/nodejs/Release - so this won't be the last time you face such an issue while running on v4

**Comment by liuzhen2008** [comment]
Thanks for the work around - tested and it works

Also thanks for the heads up regarding v4.
