### ISSUE TITLE
queryParameter doesn't change the global language automatically, and i18n.setLocale doesn't work also.

### ISSUE THREAD

**Issue by kentkrantz** [mashpie/i18n-node#402]
It looks like `queryParameter` in the configuration should automatically change the language for global if you ever passed in ?lang=de, but in fact it only changes one time, and reverts back if the url has no ?lang=de, why doesn't it change the language for global?
So I have to make my own logic, but found i18n.setLocale only change the scope language not the global, any ideas?

```javascript
i18n.configure({
    locales: ['en', 'de'],
    directory: __dirname + '/i18n',
    cookie: 'language',
    queryParameter: 'lang',
    defaultLocale: 'en'
});


app.use(function (req, res, next) {
    if (req.query.lang && ['en', 'de'].includes(req.query.lang)) {
        i18n.setLocale(req.query.lang);

        // I  have to use session to remember it for global by myself, i18n.setLocale doesn't work
        req.session.locale = req.query.lang;
    }
    if (req.session.locale) {
        i18n.setLocale(res, req.session.locale);
    }
    next();
});
```

**Comment by ventr1x** [comment]
Not only that, it changes once and then keeps that language.
I for example tested it with defaultLanguage 'de'.
Request 'de' => German
Request 'en' => English
Request 'de' => English
=> Need to restart server to change back to German

Useless plugin as it seems.

**Comment by mashpie** [comment]
@ventr1x please check scopes (or provide your example)

`i18n` sets locales to different scopes:

1) globally usefull in cli only: `i18n.setLocale('en')`
2) to current request in webapps: `i18n.setLocale(req, 'en')` or `req.setLocale('en')`  
3) to current response in webapps: `i18n.setLocale(res, 'en')` or `res.setLocale('en')`  

but it _never persists_ because each request will need to be handled within it's own current locale.

In express or any other connect based webapp you may find `app.use(i18n.init)` usefull, which does a couple of things:

- binds i18n api to `req`, `res` and `res.locals` objects
- guesses current requests language by (in order) `accept-language` header, `cookie` (if configured), `query-param` (if configured) - the later overwrites
- sets that guessed locale as current locale to `req`, `res` and `res.locals` objects

In webapps you __SHOULD__ always use scoped objects (`req`, `res` and `res.locals`) for translating requests and/or responses to the current user.

Persistance is either provided by the users browser sending it's `accept-language` header or sending a `cookie` containing the current users desired locale (ie.: `lang=en`). Setting that cookie is an implementation detail totally up to the architectur, framework or preferences of the developer. The `query-param` for example can be used to either set any initial locale for a current user or overwrite it by appending to any given route.

That beeing said..

@kentkrantz I gues you should be happy with changing your middleware to. And please don't mix global and request scopes.

```js
// need cookieParser middleware before we can do anything with cookies
app.use(express.cookieParser());

// includes setting locale by either req.session.locale or req.query.lang
app.use(i18n.init) 

app.use(function (req, res, next) {
  // as you configured 'language' as cookiename, set it to current requests locale
  res.cookie('language', res.getLocale(), { // cookie options })
  next();
});
```
