### ISSUE TITLE
Error in Typescript build creation

### ISSUE THREAD

**Issue by nmajethiya** [mashpie/i18n-node#440]
I am receiving below error

node_modules/@types/express-serve-static-core/index.d.ts(505,18): error TS2430: Interface 'Response<ResBody>' incorrectly extends interface 'Response'.
  Types of property 'locals' are incompatible.
    Type 'Record<string, any>' is missing the following properties from type 'i18nAPI': locale, __, __n, __mf, and 5 more.
src/middleware/index.ts(12,11): error TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type '(request: Request, response: Response, next?: (() => void) | undefined) => void' is not assignable to parameter of type 'PathParams'.
      Type '(request: Request, response: Response, next?: (() => void) | undefined) => void' is missing the following properties from type '(string | RegExp)[]': pop, push, concat, join, and 25 more.
The command '/bin/sh -c tsc' returned a non-zero code: 2

Kindly help with the solution

**Comment by shi-rudo** [comment]
🚨 same problem here 🚨, app suddenly stopped working 

```
node_modules/@types/express-serve-static-core/index.d.ts:505:18 - error TS2430: Interface 'Response<ResBody>' incorrectly extends interface 'Response'.
  Types of property 'locals' are incompatible.
    Type 'Record<string, any>' is missing the following properties from type 'i18nAPI': locale, __, __n, __mf, and 5 more.

505 export interface Response<ResBody = any> extends http.ServerResponse, Express.Response {
                     ~~~~~~~~

```

**Comment by mashpie** [comment]
i18n was build in plain js. There is a `@types/i18n` module (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/i18n/index.d.ts) but I am not related with that.

i18n will add more prototypes to req & res objects inherited from express or any similar web framework as written here https://github.com/mashpie/i18n-node#i18ninit

Could be an issue with express types too... or simply server-static dropped `locals` property? I don't know. Plus I don't do any ts, yet.

**Comment by shi-rudo** [comment]
okay, so in the meantime we could use "skipLibCheck": true (tsconfig.json) as workaround ...

**Comment by woodcockjosh** [comment]
@mashpie We might consider changing `locals` to `locales` or some other property name which would be a breaking change to i18n. To me this is the right solution otherwise there is is a conflict with `express-serve-static-core`. Alternatively we can drop types for `locals` as a short term workaround. I can open a PR either way. let me know.

**Comment by mashpie** [comment]
@woodcockjosh i18n provides `locales` not `locals`. `locals`refer to `res.locals` inherited from express (https://expressjs.com/de/api.html#res):

> res.locals
> An object that contains response local variables scoped to the request, and therefore available only to the view(s) rendered during that request / response cycle (if any). Otherwise, this property is identical to app.locals.
>
> This property is useful for exposing request-level information such as the request path name, authenticated user, user settings, and so on.

ex., objects provided by express:

```js
{
  req: {
    locals: {}
    res: {
      locals: {}
    }
  },
  res: {
    locals: {}
  }
}
```

and i18n decorating each `locals` property like:

```js
locals: {
  locale: "de",
  __: [function],
  __n: [function],
  [...]
}
```

pluss attaching to `req` and `res` respectively:

```js
req: {
  locale: "de",
  __: [function],
  __n: [function],
  [...]
}

res: {
  locale: "de",
  __: [function],
  __n: [function],
  [...]
}
```

So... `i18n` does not introduce `locals` but is using that property.

**Comment by woodcockjosh** [comment]
@mashpie Yes I understand we are not introducing a new variable. Unless we want to update `locals` to implement the types from `express-serve-static-core` we'll have to update the name.

**Comment by mashpie** [comment]
...well as express docs tell https://expressjs.com/en/api.html#res.locals - is an Object wich means pretty much anything in plain js.

**Comment by woodcockjosh** [comment]
We can always update `@types/i18n` to be like so
```typescript
    interface Response extends i18nAPI {
        locals: any;
    }
```
I think as long as developers don't have a breaking build they will be happy 😄

**Comment by mashpie** [comment]
to be honest... drop it. i18n just decorates `res.locals` (the response object as it comes from express) if present. In the same way it decorates `res` or any other object one want to bind it to. Please check my comment in PR. Yes locals and locales - are confusingly similar property names. But i18n is not the origin of locals - simply not.

**Comment by woodcockjosh** [comment]
There is an active PR open to update `@types/i18n` in an attempt to resolve this issue I think. I hope that PR owner will make the requested change. 
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46328

**Comment by mashpie** [comment]
Ok, thanks for support. To shed some extra light on "design decision": some (most?) express template engines use `res.locals` to attach their render helpers. To provide i18n api as template helpers to hbs and mustache for example res.locals got decorated by i18n api (https://github.com/mashpie/i18n-node#attaching-helpers-for-template-engines) - so this might be "by design" but is not "designed" at all ;)

I guess the design decision on using `res.locals` as a scope to provide some _local_ response specific... data, objects... whatever... without being shared (or even mutated) between subsequent requests was made in early stages of express by TJ himself - long before anyone thinking about pushing js prototypes into any strict typed structs. And back than it was the only way to provide that kind of encapsulation throughout concurrent request without any ES6 or TS... there are probably some more parts of this world that won't fit into strict typed expectations... sry - I had to say this :) And no I don't want to argue against strict types, but they have costs.

**Comment by niekvb** [comment]
This issue should be resolved as soon as [this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46328) merges and packages are updated.

**Comment by mashpie** [comment]
related #444
