### ISSUE TITLE
req.__("title") returns title. Same with other names/params.

### ISSUE THREAD

**Issue by rovelhub** [mashpie/i18n-node#470]
```js
var i18n = require("i18n");
i18n.configure({
 locales: ["en", "hi"],
 cookie: "lang",
 queryParameter: "lang",
 defaultLocale: "hi",
 directory: path.resolve("node_modules/rdl-i18n/site")
});
app.use(i18n.init);
app.get("/test",(req, res)=>{
res.send(res.__("title"));
});
```
On visiting /test, it returns title and not the content of title, ie. "Rovel Discord List"
Here's the main repo: https://github.com/rovelstars/discord-list
File: `src/server/app.js`

Here's the locale:
https://github.com/rovelstars/rdl-i18n

**Comment by mashpie** [comment]
could be missing cookieParser (https://github.com/mashpie/i18n-node#i18ninit) 'title' (the key) will be returned in case the target locale is set to a language not yet translated.

Also, please check value `res.locale` and `req.locale`respectively.. should read similar to 

```js
{
  req: {
    locals: {
      locale: "de",
      __: [function],
      __n: [function],
      [...]
    },
    res: {
      locals: {
        locale: "de",
        __: [function],
        __n: [function],
        [...]
      },
      locale: "de",
      __: [function],
      __n: [function],
      [...]
    },
    locale: "de",
    __: [function],
    __n: [function],
    [...]
  }
} 
```

if not, language guessing is broken because of either missing or invalid cookie value or query param or browser header.

**Comment by rovelhub** [comment]
Ok let me log the req and res locale.

**Comment by rovelhub** [comment]
Ah yes you were correct, it will send title if the language wasn't translated.
