### ISSUE TITLE
Support for Koa

### ISSUE THREAD

**Issue by Thomasdezeeuw** [mashpie/i18n-node#90]
[Koa](https://github.com/koajs/koa) is a new framework using ES6 generator, by the creators of [Express](https://github.com/visionmedia/express). There is however a small change in the api of middleware compared to Express. Instead of having `Request` and `Responses` objects, they're using the `this` object, with similar data on the object. So the `i18n.init` middleware won't work.

I wanted to write my own middleware, however the `guessLanguage` & `applyAPItoObject` functions are private, so it's rather difficult. I was wondering if Koa support is planned, or if maybe both those functions could be exposed so that I could write some middleware for Koa.

**Comment by gtomitsuka** [comment]
Any updates on this?

**Comment by mashpie** [comment]
how about a simple integration like so:

```js
app.use(function *(){
  i18n.init(this.request, this.response); // --> emulates express/connect like interface
});
```

**Comment by dustinschultz** [comment]
Make sure you don't forget to yield to next:

```
app.use(function *(next) {
    i18n.init(this.request, this.response);
    yield next;
  });
```

then 
```
this.response.__('foo');
```

**Comment by LucianoGanga** [comment]
Is it possible to make a change to include all the API inside the this.state object? 

That's a clear way to do this in KOA. I think that maybe exposing the `applyAPItoObject` method can be enough to make this happen. Besides, it can be a nice method to have public. 

Thanks!
Luciano

**Comment by LucianoGanga** [comment]
I just made a little hack, by passing the `this.state` object instead of the `this.res` object in the `i18n.init` method. I saw the code and that parameter is only used to apply the API on it, so it solves my problem. 

Hope this helps someone else!

Cheers, 
Luciano

**Comment by niftylettuce** [comment]
For anyone interested, @crocodilejs uses this package in the framework https://github.com/crocodilejs/crocodile-node-mvc-framework, but written with some cool glue on top.  I didn't want to fork this because there are so many other i18n packages out there to confuse people with.  But maybe I should?

Here's the code for anyone interested:

<https://github.com/crocodilejs/crocodile-node-mvc-framework/blob/294407e84a0d9c4377d0f9fe237b2a7278c6a028/src/helpers/i18n.js>

Basically you do `app.use(i18n.middleware);` first, and then follow it with `app.use(i18n.redirect);` second.  This is for locale support in URL's though.

If anyone ends up looking into this, I recommend you join us in Slack for more discussion and insight into what we're doing with CrocodileJS!  <http://slack.crocodilejs.com>

Some screenshots of what we're doing using this package below... 

![screen shot 2016-10-06 at 12 34 54 am](https://cloud.githubusercontent.com/assets/523141/19140634/c69b5456-8b5c-11e6-89de-4ce7519230c7.png)
![screen shot 2016-10-06 at 12 33 37 am](https://cloud.githubusercontent.com/assets/523141/19140637/c6a8e2ec-8b5c-11e6-9255-8859833eebbe.png)
![screen shot 2016-10-06 at 12 33 33 am](https://cloud.githubusercontent.com/assets/523141/19140636/c6a54722-8b5c-11e6-83b7-4d3ea3632012.png)
![screen shot 2016-10-06 at 12 33 27 am](https://cloud.githubusercontent.com/assets/523141/19140635/c6a52e22-8b5c-11e6-846a-96457bc7f92f.png)


cc @mashpie 👍 thank you for making this ❤️ ✨ 🦄

**Comment by niftylettuce** [comment]
**Just a heads up to anyone reading this or subscribed to this thread:**

I have put this logic into its own package on NPM (see link below) so you don't have to look at some outdated helper function referenced in the previous comment.

Also note that I changed it from binding i18n translation API methods like `i18n.t` from `ctx.req.t` to `ctx.request.t`.  The reason for this major change is that it's probably bad practice to bind properties on top of a Node request object and not the Koa request object.  In the latest version `@ladjs/i18n@1.0.0` it binds i18n API methods to `ctx.request` object and `ctx.state`.  All tests pass.

Docs: https://github.com/ladjs/i18n
Site: https://lad.js.org

**Comment by mashpie** [comment]
:)
